### ISSUE TITLE
coefs

### ISSUE THREAD

**Issue by owos** [CVxTz/IntegratedGradientsPytorch#1]
I'm a bit new to Stats. Please could share what `coefs`, the role it plays and how possible how it can be computed for a tabular data classification task?
Ref:
https://github.com/CVxTz/IntegratedGradientsPytorch/blob/760c88490e6b9df68f26de566dea9d06e49dd208/code/mlp_gradient.py#L97

**Comment by CVxTz** [comment]
This is just a toy example where I define the relationship between X and Y and then use integrated gradient to see if the method can discover this relationship on its own.

**Comment by owos** [comment]
Thank you for your response. I understand now.
